CupCarbon v. 3.3.11 (U-One)
----------------
name:hello_world
zoom:0
centerposition_la:-22.81495359777847
centerposition_lo:-47.06434607505798
map:10
display_details:true
draw_radio_links:false
draw_sensor_arrows:false
radio_links_color:2
draw_marker_arrows:false
display_rl_distance:false
propagation:false
display_marker_distance:false
display_radio_messages:true
draw_script_file_name:true
display_print_messages:true
